### ISSUE TITLE
how to change the icon for New File.app

### ISSUE THREAD

**Issue by GorvGoyl** [RomanSmolka/finder-new-file#2]
icon is looking out of place on Monterey.. any way to replace it?

![screenshot 2022-05-26 at 10 43 51](https://user-images.githubusercontent.com/7106086/170420778-6faea031-69ce-47b1-949b-416a9b5f501a.png)

**Comment by martingarnett01** [comment]
It's _not perfect_, but I created this plus icon for myself:

![plus-icon](https://user-images.githubusercontent.com/9989080/209945626-895fe3e6-32d1-4005-aba5-b74a57adb25a.png)

I'm curring on Ventura (13.0.1). 

To apply this image:
1. Download that image
2. Select the image (single left-click)
3. Copy the image (CMD + C)
4. Navigate to the New File.app in your applications
5. Select the app (single left-click)
6. Get Info (CMD + I)
7. Single left-click the current icon (A blue ring should appear around it)
8. Paste the new image (CMD + V)

This should update the image for the app icon, and also update it in your toolbar. 

Sadly, it doesn't have a nice background hover, but at least it looks a little closer:

<img width="992" alt="image" src="https://user-images.githubusercontent.com/9989080/209946001-9ecd3e54-a42e-49a3-84a4-42c8f32548ca.png">

**Comment by ManeLippert** [comment]
Hello all,

I had have the same issue as you and made this appoarch for an new icon:

![new-file-icon](https://user-images.githubusercontent.com/73902879/226759628-6492752c-7d6d-4ada-b74c-3ab731279617.png)
<img width="667" alt="Bildschirm­foto 2023-03-21 um 23 53 54" src="https://user-images.githubusercontent.com/73902879/226759758-58cbf0ec-39c1-4e31-a381-5a1f592fdb8b.png">

Hope you like it!

**Comment by RomanSmolka** [comment]
I just released a new version with updated icons. Just download the archive from Releases and pick the app with the preferred icon. Unfortunately there is currently no way to switch the icon automatically when changing system appearance.
