### ISSUE TITLE
In New File.app there is a binary executable

### ISSUE THREAD

**Issue by vvaltchev** [RomanSmolka/finder-new-file#3]
Hello @RomanSmolka,
your mini-project looks cool to me. The only problem I see is that there is a pre-compiled binary in the .app directory.

It will be great if you shared the full source of the application with the Xcode project files etc. You know, people trust open source software more :-)

**Comment by vvaltchev** [comment]
Thanks for taking the time to answer so accurately with a video, @mayeenulislam! I didn't know that.

In this case, I'd recommend to simply remove the binary file from the repo as people typically don't trust binary files. In particular people looking for an open source project on Github to compile. You could move this video in the README file, so that people will follow it themselves. If you want also to offer people a binary file as well, you can make a release in Github and attach a zip with the pre-compiled binary there.

But other than that, great work. Thanks for writing it!

**Comment by RomanSmolka** [comment]
@vvaltchev I just released a new version and removed the app bundle from the repo. It can now be downloaded from [Releases](https://github.com/RomanSmolka/finder-new-file/releases/latest) with different icon versions. 

As @mayeenulislam already said, the source code is the `New File.applescript` file and the app bundles are exported directly from Script Editor.
