### ISSUE TITLE
Dark mode icon

### ISSUE THREAD

**Issue by brzzdev** [RomanSmolka/finder-new-file#4]
A dark mode icon version would be great. Looks a little off, atm.

![Screenshot 2024-01-11 at 18 08 00](https://github.com/RomanSmolka/finder-new-file/assets/15687450/602d5172-8a13-4ffb-8ab2-cf6cbefb4e8f)

**Comment by RomanSmolka** [comment]
@brzzdev Thanks for the comment. I finally had time to update this little app for recent macOS versions. Just download the archive from [Releases](https://github.com/RomanSmolka/finder-new-file/releases/latest) and pick the app with the preferred icon. Unfortunately there is currently no way to switch the icon automatically when changing system appearance.
